// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/options.proto

package identifierv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentifierOptions configures code generation for identifier messages.
//
// CONSTRAINT: Messages with this option MUST have exactly ONE scalar field.
// The plugin automatically uses that single field as the underlying value.
// This enforces the semantic definition of an identifier: a typed wrapper
// around a single primitive value.
type IdentifierOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// skip_unwrap disables generation of Unwrap() method.
	SkipUnwrap bool `protobuf:"varint,1,opt,name=skip_unwrap,json=skipUnwrap,proto3" json:"skip_unwrap,omitempty"`
	// skip_equal disables generation of Equal() method.
	SkipEqual bool `protobuf:"varint,2,opt,name=skip_equal,json=skipEqual,proto3" json:"skip_equal,omitempty"`
	// skip_clone disables generation of Clone() method.
	SkipClone bool `protobuf:"varint,3,opt,name=skip_clone,json=skipClone,proto3" json:"skip_clone,omitempty"`
	// skip_constructor disables generation of As<Type>() function.
	SkipConstructor bool `protobuf:"varint,4,opt,name=skip_constructor,json=skipConstructor,proto3" json:"skip_constructor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdentifierOptions) Reset() {
	*x = IdentifierOptions{}
	mi := &file_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifierOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifierOptions) ProtoMessage() {}

func (x *IdentifierOptions) ProtoReflect() protoreflect.Message {
	mi := &file_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifierOptions.ProtoReflect.Descriptor instead.
func (*IdentifierOptions) Descriptor() ([]byte, []int) {
	return file_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifierOptions) GetSkipUnwrap() bool {
	if x != nil {
		return x.SkipUnwrap
	}
	return false
}

func (x *IdentifierOptions) GetSkipEqual() bool {
	if x != nil {
		return x.SkipEqual
	}
	return false
}

func (x *IdentifierOptions) GetSkipClone() bool {
	if x != nil {
		return x.SkipClone
	}
	return false
}

func (x *IdentifierOptions) GetSkipConstructor() bool {
	if x != nil {
		return x.SkipConstructor
	}
	return false
}

var file_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*IdentifierOptions)(nil),
		Field:         74000,
		Name:          "plugins.identifier.v1.identifier",
		Tag:           "bytes,74000,opt,name=identifier",
		Filename:      "v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// identifier marks a message as an identifier type and enables
	// automatic helper method generation.
	//
	// Usage:
	//
	//	message FooID {
	//	  option (plugins.identifier.v1.identifier) = {};
	//	  string id = 1;
	//	}
	//
	// The message MUST have exactly one scalar field. The plugin
	// auto-detects that field for Unwrap(), etc.
	//
	// optional plugins.identifier.v1.IdentifierOptions identifier = 74000;
	E_Identifier = &file_v1_options_proto_extTypes[0]
)

var File_v1_options_proto protoreflect.FileDescriptor

const file_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x10v1/options.proto\x12\x15plugins.identifier.v1\x1a google/protobuf/descriptor.proto\"\x9d\x01\n" +
	"\x11IdentifierOptions\x12\x1f\n" +
	"\vskip_unwrap\x18\x01 \x01(\bR\n" +
	"skipUnwrap\x12\x1d\n" +
	"\n" +
	"skip_equal\x18\x02 \x01(\bR\tskipEqual\x12\x1d\n" +
	"\n" +
	"skip_clone\x18\x03 \x01(\bR\tskipClone\x12)\n" +
	"\x10skip_constructor\x18\x04 \x01(\bR\x0fskipConstructor:k\n" +
	"\n" +
	"identifier\x12\x1f.google.protobuf.MessageOptions\x18\x90\xc2\x04 \x01(\v2(.plugins.identifier.v1.IdentifierOptionsR\n" +
	"identifierB\xe1\x01\n" +
	"\x19com.plugins.identifier.v1B\fOptionsProtoP\x01Z@github.com/OldBigBuddha/protoc-gen-go-identifier/v1;identifierv1\xa2\x02\x03PIX\xaa\x02\x15Plugins.Identifier.V1\xca\x02\x15Plugins\\Identifier\\V1\xe2\x02!Plugins\\Identifier\\V1\\GPBMetadata\xea\x02\x17Plugins::Identifier::V1b\x06proto3"

var (
	file_v1_options_proto_rawDescOnce sync.Once
	file_v1_options_proto_rawDescData []byte
)

func file_v1_options_proto_rawDescGZIP() []byte {
	file_v1_options_proto_rawDescOnce.Do(func() {
		file_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_options_proto_rawDesc), len(file_v1_options_proto_rawDesc)))
	})
	return file_v1_options_proto_rawDescData
}

var file_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_options_proto_goTypes = []any{
	(*IdentifierOptions)(nil),           // 0: plugins.identifier.v1.IdentifierOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_v1_options_proto_depIdxs = []int32{
	1, // 0: plugins.identifier.v1.identifier:extendee -> google.protobuf.MessageOptions
	0, // 1: plugins.identifier.v1.identifier:type_name -> plugins.identifier.v1.IdentifierOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_options_proto_init() }
func file_v1_options_proto_init() {
	if File_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_options_proto_rawDesc), len(file_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_v1_options_proto_goTypes,
		DependencyIndexes: file_v1_options_proto_depIdxs,
		MessageInfos:      file_v1_options_proto_msgTypes,
		ExtensionInfos:    file_v1_options_proto_extTypes,
	}.Build()
	File_v1_options_proto = out.File
	file_v1_options_proto_goTypes = nil
	file_v1_options_proto_depIdxs = nil
}
