// Code generated by protoc-gen-go-identifier. DO NOT EDIT.
// source: cmd/protoc-gen-go-identifier/testdata/test.proto

package testdata

import (
	"bytes"
	"google.golang.org/protobuf/proto"
)

// AsStringID creates a new StringID from the given value.
func AsStringID(v string) *StringID {
	return &StringID{Id: v}
}

// Unwrap returns the underlying value. Returns "" if receiver is nil.
func (x *StringID) Unwrap() string {
	if x == nil {
		return ""
	}
	return x.Id
}

// Equal reports whether x and other have the same underlying value.
func (x *StringID) Equal(other *StringID) bool {
	return x.Unwrap() == other.Unwrap()
}

// Clone returns a deep copy of the StringID.
func (x *StringID) Clone() *StringID {
	return proto.Clone(x).(*StringID)
}

// AsIntID creates a new IntID from the given value.
func AsIntID(v int64) *IntID {
	return &IntID{Id: v}
}

// Unwrap returns the underlying value. Returns 0 if receiver is nil.
func (x *IntID) Unwrap() int64 {
	if x == nil {
		return 0
	}
	return x.Id
}

// Equal reports whether x and other have the same underlying value.
func (x *IntID) Equal(other *IntID) bool {
	return x.Unwrap() == other.Unwrap()
}

// Clone returns a deep copy of the IntID.
func (x *IntID) Clone() *IntID {
	return proto.Clone(x).(*IntID)
}

// AsBytesID creates a new BytesID from the given value.
func AsBytesID(v []byte) *BytesID {
	return &BytesID{Data: v}
}

// Unwrap returns the underlying value. Returns nil if receiver is nil.
func (x *BytesID) Unwrap() []byte {
	if x == nil {
		return nil
	}
	return x.Data
}

// Equal reports whether x and other have the same underlying value.
func (x *BytesID) Equal(other *BytesID) bool {
	return bytes.Equal(x.Unwrap(), other.Unwrap())
}

// Clone returns a deep copy of the BytesID.
func (x *BytesID) Clone() *BytesID {
	return proto.Clone(x).(*BytesID)
}

// Unwrap returns the underlying value. Returns "" if receiver is nil.
func (x *PartialID) Unwrap() string {
	if x == nil {
		return ""
	}
	return x.Id
}

// Equal reports whether x and other have the same underlying value.
func (x *PartialID) Equal(other *PartialID) bool {
	return x.Unwrap() == other.Unwrap()
}
