// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cmd/protoc-gen-go-identifier/testdata/test.proto

package testdata

import (
	_ "github.com/OldBigBuddha/protoc-gen-go-identifier/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StringID is an identifier with a string field.
type StringID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringID) Reset() {
	*x = StringID{}
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringID) ProtoMessage() {}

func (x *StringID) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringID.ProtoReflect.Descriptor instead.
func (*StringID) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescGZIP(), []int{0}
}

func (x *StringID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// IntID is an identifier with an int64 field.
type IntID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntID) Reset() {
	*x = IntID{}
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntID) ProtoMessage() {}

func (x *IntID) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntID.ProtoReflect.Descriptor instead.
func (*IntID) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescGZIP(), []int{1}
}

func (x *IntID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// BytesID is an identifier with a bytes field.
type BytesID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesID) Reset() {
	*x = BytesID{}
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesID) ProtoMessage() {}

func (x *BytesID) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesID.ProtoReflect.Descriptor instead.
func (*BytesID) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescGZIP(), []int{2}
}

func (x *BytesID) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PartialID only generates some methods.
type PartialID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialID) Reset() {
	*x = PartialID{}
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialID) ProtoMessage() {}

func (x *PartialID) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialID.ProtoReflect.Descriptor instead.
func (*PartialID) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescGZIP(), []int{3}
}

func (x *PartialID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// NoOptionMessage should not generate any identifier methods.
type NoOptionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoOptionMessage) Reset() {
	*x = NoOptionMessage{}
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoOptionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoOptionMessage) ProtoMessage() {}

func (x *NoOptionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoOptionMessage.ProtoReflect.Descriptor instead.
func (*NoOptionMessage) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescGZIP(), []int{4}
}

func (x *NoOptionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NoOptionMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_cmd_protoc_gen_go_identifier_testdata_test_proto protoreflect.FileDescriptor

const file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDesc = "" +
	"\n" +
	"0cmd/protoc-gen-go-identifier/testdata/test.proto\x12\btestdata\x1a\x10v1/options.proto\" \n" +
	"\bStringID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id:\x04\x82\x91$\x00\"\x1d\n" +
	"\x05IntID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id:\x04\x82\x91$\x00\"#\n" +
	"\aBytesID\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data:\x04\x82\x91$\x00\"%\n" +
	"\tPartialID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id:\b\x82\x91$\x04\x18\x01 \x01\"5\n" +
	"\x0fNoOptionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\xb1\x01\n" +
	"\fcom.testdataB\tTestProtoP\x01ZVgithub.com/OldBigBuddha/protoc-gen-go-identifier/cmd/protoc-gen-go-identifier/testdata\xa2\x02\x03TXX\xaa\x02\bTestdata\xca\x02\bTestdata\xe2\x02\x14Testdata\\GPBMetadata\xea\x02\bTestdatab\x06proto3"

var (
	file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescData []byte
)

func file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDesc), len(file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDesc)))
	})
	return file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDescData
}

var file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cmd_protoc_gen_go_identifier_testdata_test_proto_goTypes = []any{
	(*StringID)(nil),        // 0: testdata.StringID
	(*IntID)(nil),           // 1: testdata.IntID
	(*BytesID)(nil),         // 2: testdata.BytesID
	(*PartialID)(nil),       // 3: testdata.PartialID
	(*NoOptionMessage)(nil), // 4: testdata.NoOptionMessage
}
var file_cmd_protoc_gen_go_identifier_testdata_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_go_identifier_testdata_test_proto_init() }
func file_cmd_protoc_gen_go_identifier_testdata_test_proto_init() {
	if File_cmd_protoc_gen_go_identifier_testdata_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDesc), len(file_cmd_protoc_gen_go_identifier_testdata_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_go_identifier_testdata_test_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_go_identifier_testdata_test_proto_depIdxs,
		MessageInfos:      file_cmd_protoc_gen_go_identifier_testdata_test_proto_msgTypes,
	}.Build()
	File_cmd_protoc_gen_go_identifier_testdata_test_proto = out.File
	file_cmd_protoc_gen_go_identifier_testdata_test_proto_goTypes = nil
	file_cmd_protoc_gen_go_identifier_testdata_test_proto_depIdxs = nil
}
